[package]
name = "assault_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "assault_engine"
path = "src/lib.rs"


[[bin]]
name = "assault_engine_cli"
path = "src/bin.rs"
